DROP TABLE BOOK;
DROP TABLE USERS1;
DROP TABLE RENT;
DROP TABLE bookQuantity;

CREATE TABLE BOOK 
(
  BOOK_ISBN   VARCHAR2(100) NOT NULL, --ISBN
  BOOK_NUMBER	NUMBER PRIMARY KEY, --책 일련번호
  BOOK_TITLE	VARCHAR2(100)  NOT NULL, --도서 제목
  BOOK_AUTHOR	VARCHAR2(30)  NOT NULL, --저자
  BOOK_RENT_YN	CHAR(1) DEFAULT 'Y', --대여 가능여부 (BOOK_STOCK >= 1 이면 대여가능)
  BOOK_COM VARCHAR2(30) NOT NULL, -- 출판사
  BOOK_STOCK NUMBER
);


CREATE SEQUENCE BOOK_SEQ
       INCREMENT BY 1
       START WITH 1001
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;
DROP SEQUENCE BOOK_SEQ;


INSERT INTO BOOK 
(BOOK_ISBN, BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-3085-0816-5',BOOK_SEQ.NEXTVAL, '트렌드 코리아 2023', '김난도','Y','미래의 창');

INSERT INTO BOOK 
(BOOK_ISBN, BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-1147-3287-6',BOOK_SEQ.NEXTVAL, '아버지의 해방일지', '정지아','Y','창비');

INSERT INTO BOOK 
(BOOK_ISBN, BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-8551-9616-5',BOOK_SEQ.NEXTVAL, '조국의 법고전 산책', '조국','Y','오마이북');

INSERT INTO BOOK 
(BOOK_ISBN,BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-6180-7487-2',BOOK_SEQ.NEXTVAL, '불편한 편의점', '김호연','Y','나무옆의자');

INSERT INTO BOOK 
(BOOK_ISBN,BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM,BOOK_STOCK) 
VALUES 
('0-8000-7154-9',BOOK_SEQ.NEXTVAL, '하얼빈', '김훈','Y','문학동네',3);

INSERT INTO BOOK 
(BOOK_ISBN,BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-1378-7255-0',BOOK_SEQ.NEXTVAL, '마흔에 읽는 니체', '장재형','Y','유노북스');

INSERT INTO BOOK 
(BOOK_ISBN,BOOK_NUMBER,BOOK_TITLE,BOOK_AUTHOR,BOOK_RENT_YN,BOOK_COM) 
VALUES 
('0-3983-5335-2',BOOK_SEQ.NEXTVAL, '역행자', '자청','Y','웅진지식하우스');

CREATE TABLE bookQuantity (
    BOOK_NUMBER REFERENCES BOOK(BOOK_NUMBER), -- 도서 번호
    BOOK_TITLE VARCHAR2(100), --도서 제목
    BOOK_STOCK  NUMBER DEFAULT 1 PRIMARY KEY  -- 도서 수량
);

SELECT * FROM BOOK; 
commit;
-- ------------------------------------------------------------------------------------------------------------

CREATE TABLE USERS1 --회원 테이블
(
  USER_ID VARCHAR2(20) NOT NULL UNIQUE,
  USER_PASSWORD VARCHAR2(20) NOT NULL,
  USER_NUMBER	NUMBER PRIMARY KEY, --회원 (일련)번호  
  USER_NAME	VARCHAR2(30) NOT NULL, -- 회원 이름
  USER_PHONENUM	VARCHAR2(15), --폰번호
  USER_MAIL	VARCHAR2(50), --이메일
  USER_RENTED_BOOK VARCHAR2(20),-- 대여 도서명
  USER_RENTED_BOOK_QUANTITY NUMBER --대여 도서권수
);
CREATE SEQUENCE USER_SEQ;



INSERT INTO USERS1
(USER_ID,USER_PASSWORD,USER_NUMBER,USER_NAME,USER_PHONENUM,USER_MAIL,USER_RENTED_BOOK,USER_RENTED_BOOK_QUANTITY) 
VALUES 
('son','son',USER_SEQ.NEXTVAL, '손흥민','010-1111-1111','son@naver.com', NULL ,0);

INSERT INTO USERS1
(USER_ID,USER_PASSWORD,USER_NUMBER,USER_NAME,USER_PHONENUM,USER_MAIL,USER_RENTED_BOOK,USER_RENTED_BOOK_QUANTITY) 
VALUES 
('cha','cha',USER_SEQ.NEXTVAL, '차범근','010-5555-5555','cha@naver.com', NULL ,0);
INSERT INTO USERS1
(USER_ID,USER_PASSWORD,USER_NUMBER,USER_NAME,USER_PHONENUM,USER_MAIL,USER_RENTED_BOOK,USER_RENTED_BOOK_QUANTITY) 
VALUES 
('park','park',USER_SEQ.NEXTVAL, '박지성','010-4444-4444','park@naver.com', NULL ,0);
INSERT INTO USERS1
(USER_ID,USER_PASSWORD,USER_NUMBER,USER_NAME,USER_PHONENUM,USER_MAIL,USER_RENTED_BOOK,USER_RENTED_BOOK_QUANTITY) 
VALUES 
('lee','lee',USER_SEQ.NEXTVAL, '이강인','010-3333-3333','lee@naver.com', NULL ,0);
INSERT INTO USERS1
(USER_ID,USER_PASSWORD,USER_NUMBER,USER_NAME,USER_PHONENUM,USER_MAIL,USER_RENTED_BOOK,USER_RENTED_BOOK_QUANTITY) 
VALUES 
('kim','kim',USER_SEQ.NEXTVAL, '김민재','010-2222-2222','kim@naver.com', NULL ,0);


SELECT * FROM USERS1;



---------------------------------------------------------------------------------------------------------------------
CREATE TABLE RENT 
(
  RENT_NUMBER	NUMBER PRIMARY KEY, --대여 (일련)번호
  USER_NUMBER	NUMBER NOT NULL REFERENCES USERS1(USER_NUMBER), --회원 일련번호 (누가 빌려갔는지)
  BOOK_NUMBER	NUMBER NOT NULL REFERENCES BOOK(BOOK_NUMBER), --도서 일련번호 (어떤 책을 빌려갔는지)
  RENT_DATE	DATE, --도서 대출일 (언제 빌려갔는지)
  RENT_RETURN_DATE	DATE, --도서 반납 예정일 (도서대출일+20)
  RENT_RETURN_YN CHAR(1), -- 도서 반납 여부(Y/N)
  BOOK_STOCK NUMBER REFERENCES bookQuantity(BOOK_STOCK) --도서 수량 (현재 몇권 남아있는지)
);
SELECT * FROM RENT;

CREATE SEQUENCE RENT_SEQ;